print("Seja bem vindo ao sistema de regra de 3")
print(" A está para B assim como C esta para X")
A = float(input("Digite o valor de A: "))
B = float(input("Digite o valor de B: "))
C = float(input("Digite o valor de C: "))
